# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://qingwang.li/blog
date_format: "ordinal"
title: 小我 | Syauo
subtitle: "学贵有恒 驽马奋蹄"
description: ""
keywords: 小我, Syauo
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: Li.Q.W.
organization: G.F.
organization_url: 
github_username: syauo
location: Weihai, China
email: lqw@gmx.li

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
    
  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

#  -
#    href: /links/
#    label: 链接

#  -
#    href: /about/
#    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: syauo/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: syauo
    repo: blog-comments
    oauth:
        client_id: d8378284ac37cfe4b998
        client_secret: 0c56cc87b8ca78044e7f99ad6fe01fdca5587265
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: syauo
    repo: blog-comments
    clientID: d8378284ac37cfe4b998
    clientSecret: 0c56cc87b8ca78044e7f99ad6fe01fdca5587265
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-116307746-1 
